export type Database = {
  public: {
    Tables: {
      clients: {
        Row: {
          id: string;
          company_name: string;
          department: string | null;
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          payment_terms: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_name: string;
          department?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          payment_terms?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_name?: string;
          department?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          payment_terms?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      contracts: {
        Row: {
          id: string;
          client_id: string | null;
          project_name: string;
          contract_type: string;
          unit_price: number | null;
          quantity: number;
          total_amount: number;
          vat_included: boolean;
          advance_rate: number;
          advance_amount: number | null;
          balance_amount: number | null;
          contract_start: string | null;
          contract_end: string | null;
          delivery_deadline: string | null;
          status: string;
          contract_pdf_url: string | null;
          pm_id: string | null;
          created_by: string | null;
          ai_generated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id?: string | null;
          project_name: string;
          contract_type?: string;
          unit_price?: number | null;
          quantity?: number;
          total_amount: number;
          vat_included?: boolean;
          advance_rate?: number;
          advance_amount?: number | null;
          balance_amount?: number | null;
          contract_start?: string | null;
          contract_end?: string | null;
          delivery_deadline?: string | null;
          status?: string;
          contract_pdf_url?: string | null;
          pm_id?: string | null;
          created_by?: string | null;
          ai_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string | null;
          project_name?: string;
          contract_type?: string;
          unit_price?: number | null;
          quantity?: number;
          total_amount?: number;
          vat_included?: boolean;
          advance_rate?: number;
          advance_amount?: number | null;
          balance_amount?: number | null;
          contract_start?: string | null;
          contract_end?: string | null;
          delivery_deadline?: string | null;
          status?: string;
          contract_pdf_url?: string | null;
          pm_id?: string | null;
          created_by?: string | null;
          ai_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          contract_id: string | null;
          payment_type: string;
          amount: number;
          vat_amount: number | null;
          total_with_vat: number | null;
          invoice_date: string | null;
          due_date: string | null;
          tax_invoice_date: string | null;
          status: string;
          paid_date: string | null;
          paid_amount: number | null;
          reminder_sent: boolean;
          overdue_days: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          contract_id?: string | null;
          payment_type: string;
          amount: number;
          vat_amount?: number | null;
          total_with_vat?: number | null;
          invoice_date?: string | null;
          due_date?: string | null;
          tax_invoice_date?: string | null;
          status?: string;
          paid_date?: string | null;
          paid_amount?: number | null;
          reminder_sent?: boolean;
          overdue_days?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          contract_id?: string | null;
          payment_type?: string;
          amount?: number;
          vat_amount?: number | null;
          total_with_vat?: number | null;
          invoice_date?: string | null;
          due_date?: string | null;
          tax_invoice_date?: string | null;
          status?: string;
          paid_date?: string | null;
          paid_amount?: number | null;
          reminder_sent?: boolean;
          overdue_days?: number;
          created_at?: string;
        };
      };
      freelancers: {
        Row: {
          id: string;
          name: string;
          specialty: string | null;
          daily_rate: number | null;
          bank_name: string | null;
          account_number: string | null;
          account_holder: string | null;
          phone: string | null;
          email: string | null;
          tax_type: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          specialty?: string | null;
          daily_rate?: number | null;
          bank_name?: string | null;
          account_number?: string | null;
          account_holder?: string | null;
          phone?: string | null;
          email?: string | null;
          tax_type?: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          specialty?: string | null;
          daily_rate?: number | null;
          bank_name?: string | null;
          account_number?: string | null;
          account_holder?: string | null;
          phone?: string | null;
          email?: string | null;
          tax_type?: string;
          notes?: string | null;
          created_at?: string;
        };
      };
      freelancer_assignments: {
        Row: {
          id: string;
          contract_id: string | null;
          freelancer_id: string | null;
          work_days: number | null;
          daily_rate: number | null;
          total_fee: number | null;
          withholding_tax: number | null;
          net_payment: number | null;
          payment_status: string;
          paid_date: string | null;
          early_payment: boolean;
          early_payment_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          contract_id?: string | null;
          freelancer_id?: string | null;
          work_days?: number | null;
          daily_rate?: number | null;
          total_fee?: number | null;
          withholding_tax?: number | null;
          net_payment?: number | null;
          payment_status?: string;
          paid_date?: string | null;
          early_payment?: boolean;
          early_payment_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          contract_id?: string | null;
          freelancer_id?: string | null;
          work_days?: number | null;
          daily_rate?: number | null;
          total_fee?: number | null;
          withholding_tax?: number | null;
          net_payment?: number | null;
          payment_status?: string;
          paid_date?: string | null;
          early_payment?: boolean;
          early_payment_reason?: string | null;
          created_at?: string;
        };
      };
      employees: {
        Row: {
          id: string;
          name: string;
          position: string | null;
          department: string | null;
          hire_date: string | null;
          contract_type: string | null;
          probation_end_date: string | null;
          salary: number | null;
          bank_account: string | null;
          phone: string | null;
          email: string | null;
          emergency_contact: string | null;
          annual_leave_total: number;
          annual_leave_used: number;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          position?: string | null;
          department?: string | null;
          hire_date?: string | null;
          contract_type?: string | null;
          probation_end_date?: string | null;
          salary?: number | null;
          bank_account?: string | null;
          phone?: string | null;
          email?: string | null;
          emergency_contact?: string | null;
          annual_leave_total?: number;
          annual_leave_used?: number;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          position?: string | null;
          department?: string | null;
          hire_date?: string | null;
          contract_type?: string | null;
          probation_end_date?: string | null;
          salary?: number | null;
          bank_account?: string | null;
          phone?: string | null;
          email?: string | null;
          emergency_contact?: string | null;
          annual_leave_total?: number;
          annual_leave_used?: number;
          status?: string;
          created_at?: string;
        };
      };
      attendance: {
        Row: {
          id: string;
          employee_id: string | null;
          date: string;
          type: string;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          employee_id?: string | null;
          date: string;
          type: string;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string | null;
          date?: string;
          type?: string;
          note?: string | null;
          created_at?: string;
        };
      };
      project_schedules: {
        Row: {
          id: string;
          contract_id: string | null;
          phase: string;
          phase_name: string | null;
          start_date: string | null;
          end_date: string | null;
          status: string;
          assigned_to: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          contract_id?: string | null;
          phase: string;
          phase_name?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          assigned_to?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          contract_id?: string | null;
          phase?: string;
          phase_name?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          assigned_to?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
